config/routes.rb
Spree::Core::Engine.add_routes do
  namespace :admin, path: Spree.admin_path do
    # resources :sheets
    get '/sheets', to: 'sheets#index'
    get '/sheets/new', to: 'sheets#new', as: :new_sheet
    post '/sheets/new', to: 'sheets#create', as: :create_new_sheet
    get '/sheets/edit/:id', to: 'sheets#edit', as: :edit_sheet
    get '/sheets/process/:id', to: 'sheets#process_file', as: :process_sheet
    get '/sheets/headers/:id', to: 'sheets#process_headers', as: :process_headers
    get '/sheets/import_products/:id', to: 'sheets#import_products', as: :import_products_sheet
    get '/sheets/get_parsed_json_files/:id', to: 'sheets#get_parsed_json_files', as: :get_parsed_json_files
    
    get '/sheets/global_map_item/:id', to: 'sheets#global_map_item', as: :sheet_global_map_item
    patch '/sheets/header_map/:id', to: 'sheets#update_header_map', as: :sheet_header_map_patch
    patch '/sheets/global_map/:id', to: 'sheets#update_global_map', as: :sheet_global_map_patch
    get '/sheets/header_map_item/:id', to: 'sheets#header_map_item', as: :sheet_header_map_item

    patch '/sheets/update/:id', to: 'sheets#update', as: :update_sheet
    delete '/sheets/delete/:id', to: 'sheets#delete', as: :delete_sheet
    get '/sheets/status/:id', to: 'sheets#sheet_status', as: :sheet_status
  end
end

app/models/spree/sheet.rb
class Spree::Sheet < ApplicationRecord

  enum status: [ :active, :processing, :failed_processing, :ready, :done, :failed ]
  has_one_attached :file
  has_many_attached :parsed_json_files

  DEFAULT_PRODUCT_PROP_VALUE = 'none'

  def self.product_props
    [DEFAULT_PRODUCT_PROP_VALUE] + [:sku, :cost_currency, :cost_price, :price, :taxons] + self.global_map_props.keys 
  end

  def self.variant_props
    [ :weight,
      :height,
      :width,
      :depth,
      :position,
      :track_inventory
    ]
  end

  def self.header_map_props
    extra_product_props = [:name, :description, :meta_description, :meta_keywords, :meta_title]
    self.product_props + extra_product_props + self.variant_props
  end

  def self.global_map_props
    {
      available_on: { 
        require_choice: false,
        multiple: false,
        data: [{id: 'now', text: 'Time.now()'}]
      },
      # TODO: date parsing...
      # discontinue_on: { 
      #   require_choice: false,
      #   multiple: false,
      #   data: [{id: 'now', text: 'Time.now()'}]
      # },
      tax_category_id: { 
        require_choice: true,
        multiple: false,
        data: Spree::TaxCategory.order(:name).map{|i| {id: i.id, text: i.name}}
      },
      shipping_category_id: { 
        require_choice: true,
        multiple: false,
        data: Spree::ShippingCategory.all.map{|i| {id: i.id, text: i.name}}
      },
      promotionable: { 
        require_choice: true,
        multiple: false,
        data: [{id: 'true', text: 'true'}, {id: 'false', text: 'false'}]
      },
      backorderable: { 
        require_choice: true,
        multiple: false,
        data: [{id: 'true', text: 'true'}, {id: 'false', text: 'false'}]
      },
      store_id: { 
        require_choice: true,
        multiple: false,
        data: Spree::Store.all.map{|store| {id: store.id, text: store.name}}
      },
      tag_list: { 
        require_choice: false,
        multiple: true,
        data: Spree::Tag.all.limit(250).map{|store| {id: store.id, text: store.name}}
      },
      property: { 
        require_choice: false,
        multiple: false,
        data: []
      },
      taxon_ids: { 
        require_choice: false,
        multiple: true,
        data: Spree::Taxon.all.limit(250).map{|i| {id: i.id, text: i.name}}
      }
      # TODO: better stock handling...
      # stock_location_id: { 
      #   require_choice: true,
      #   multiple: false,
      #   data: Spree::StockLocation.all.map{|i| {id: i.id, text: i.name}}
      # }
    }
  end

  def file_path
    # Rails.application.routes.url_helpers.rails_blob_path(sheet.file, only_path: true)
    ActiveStorage::Blob.service.path_for(file.key)
  end

  def status_class
    case status_before_type_cast
    when Spree::Sheet.statuses[:active]
      'label-primary'
    when Spree::Sheet.statuses[:processing]
      'label-info'
    when Spree::Sheet.statuses[:failed_processing]
      'label-warning'
    when Spree::Sheet.statuses[:ready]
      'label-success'
    when Spree::Sheet.statuses[:done]
      'label-default'
    when Spree::Sheet.statuses[:failed]
      'label-danger'
    end
  end

  def update_header_row
    GetSheetHeadersJob.perform_later(id)
  end

  def header_map_values
    data["header_map"].keys.collect{|k| data["header_map"][k] } rescue nil
  end

  def global_map_values
    data["global_map"].collect{|k| k[1] } rescue []
  end

  def map_cells_to_product(cells, taxon_cache={})
    product_attributes = {}
    product_attributes[:master] = {}
    product_attributes[:properties] = []

    hm_values = header_map_values
    return if hm_values.nil?
    
    # begin 
      # HEADER MAP
      hm_values.each do |hm|
        product_prop = hm["dest"]
        next if product_prop == DEFAULT_PRODUCT_PROP_VALUE
        # cell_index = hm_values.find_index{|v| v["key"] == product_prop} rescue nil
        # next if cell_index.nil? or cells[cell_index].nil?
        value = hm["keys"].split(",").map(&:to_i).collect{|i| cells[i].titleize}.join(' ') rescue ''

        unless hm["price_multiplier"].nil? or hm["price_multiplier"].to_f == 0 or value.to_f.to_s != value
          value = '%.2f' % (value.to_f * hm["price_multiplier"].to_f + value.to_f)
        end

        if product_prop == 'property'
          product_attributes[:properties] << [hm["prop_key"], value] unless hm["prop_key"].blank? or value.blank?
        elsif Spree::Product.has_attribute? product_prop or Spree::Product.method_defined? product_prop
          if product_prop == 'taxon_ids'
            product_attributes[:taxon_ids] ||= []
            product_attributes[:taxon_ids] += value.split(',').map(&:to_i)
          elsif product_prop == 'taxons'
            product_attributes[:taxon_ids] ||= []
            product_attributes[:taxon_ids] += value.split(',').collect do |v|
              v = v.strip
              if taxon_cache[v.strip].nil?
                taxon_id = Spree::Taxonomy.where("lower(name) = ?", v.downcase).first.try(:taxons).try(:first).try(:id)
                taxon_id ||= Spree::Taxonomy.where(name: v.titleize).first_or_create.try(:taxons).try(:first).try(:id)
                taxon_cache[v.strip] = taxon_id unless taxon_id.nil?
              end
              taxon_cache[v]
            end
          else
            product_attributes[product_prop.to_sym] ||= ""
            product_attributes[product_prop.to_sym] << " #{value.to_s}"
            product_attributes[product_prop.to_sym].strip!
          end
        elsif Spree::Variant.has_attribute? product_prop or Spree::Variant.method_defined? product_prop
          product_attributes[:master][product_prop.to_sym] ||= ""
          product_attributes[:master][product_prop.to_sym] << " #{value.to_s}"
          product_attributes[:master][product_prop.to_sym].stirp!
        else 
          p "[Sheet] dunno about this header :/ #{product_prop}"
        end
      end
      # GLOBAL MAP
      gm_values = global_map_values
      gm_values.each do |gm|
        next if gm["dest"].nil? or gm["key"].nil?
        gm["dest"] = Time.now if gm["dest"] == 'now'
        if gm["key"] == 'property'
          product_attributes[:properties] << [gm["prop_key"], gm["dest"]] unless gm["prop_key"].nil? or gm["dest"].nil?
        elsif Spree::Product.has_attribute? gm["key"] or Spree::Product.method_defined? gm["key"]
          if gm["key"] == 'taxon_ids'
            product_attributes[gm["key"].to_sym] ||= []
            product_attributes[gm["key"].to_sym] += gm["dest"].split(',').map(&:to_i)
          else
            product_attributes[gm["key"].to_sym] ||= ""
            product_attributes[gm["key"].to_sym] << " #{gm["dest"].to_s}"
            product_attributes[gm["key"].to_sym].strip!
          end
        elsif Spree::Variant.has_attribute? gm["key"] or Spree::Variant.method_defined? gm["key"]
          product_attributes[:master][gm["key"].to_sym] ||= ""
          product_attributes[:master][gm["key"].to_sym] << " #{gm["dest"]}"
          product_attributes[:master][gm["key"].to_sym].strip!
        else 
          p "[Sheet] dunno about this global map ref :/  #{gm["key"]}"
        end
      end

      product_attributes[:sheet_id] = id

      return product_attributes
    # rescue => err
    #   return product_attributes
    # end
  end

end
  

app/controllers/spree/admin/sheets_controller.rb
module Spree
  module Admin
    class SheetsController < Spree::Admin::ResourceController
      def index
        @sheets = Spree::Sheet.page params[:page]
      end

      def create
        @sheet = Spree::Sheet.create!(sheet_params)
        @sheet.active!
        @sheet.update_header_row
        redirect_to admin_edit_sheet_path(@sheet.id)
      end

      def edit
        @sheet = Spree::Sheet.find_by_id(params[:id])
      end

      def update
        @sheet = Spree::Sheet.find_by_id(params[:id])

        if @sheet.header_row.to_s != sheet_params[:header_row]
          @sheet.update_header_row
        end

        @sheet.update_attributes(sheet_params)
        redirect_to admin_edit_sheet_path(@sheet.id)
      end

      def delete
        @sheet_id = params[:id]
        sheet = Spree::Sheet.find_by_id(@sheet_id)
        flash[:success] = 'Sheet destroyed.'
        sheet.destroy
      end

      def process_file
        @sheet = Spree::Sheet.find_by_id(params[:id])
        if(!@sheet.processing?)
          @sheet.processing!
          ParseProductsSheetJob.perform_later(@sheet.id)
        end
        flash[:success] = 'Processing file...'
        redirect_to admin_edit_sheet_path(@sheet.id)
      end

      
      def process_headers
        @sheet = Spree::Sheet.find_by_id(params[:id])
        if(!@sheet.processing?)
          @sheet.update_header_row
        end
        flash[:success] = 'Processing Headers...'
        redirect_to admin_edit_sheet_path(@sheet.id)
      end

      def import_products
        @sheet = Spree::Sheet.find_by_id(params[:id])
        if(@sheet.active? or @sheet.ready? or @sheet.failed_processing?)
          @sheet.processing!
          ImportProductsSheetJob.perform_later(@sheet.id)
        end
        flash[:success] = 'Importing products...'
        redirect_to admin_edit_sheet_path(@sheet.id)
      end

      def get_parsed_json_files
        sheet = Spree::Sheet.find_by_id(params[:id])
        @parsed_json_files = sheet.parsed_json_files.collect{|f| f.service_url}
        render json: @parsed_json_files
      end

      def update_header_map
        log("update_header_map params: #{params['header_map']}")
        @sheet = Spree::Sheet.find_by_id(params[:id])
        
        @sheet.data['header_map'] = params["header_map"]
        @sheet.save
      end

      def update_global_map
        log("update_global_map params: #{params}")
        @sheet = Spree::Sheet.find_by_id(params[:id])
        unless params[:global_map].blank?
          @sheet.data['global_map'] = params[:global_map]
          @sheet.save
        end
      end

      def sheet_status
        @sheet = Spree::Sheet.find_by_id(params[:id])
        render json: {status: @sheet.status, progress: @sheet.data["progress"]}
      end
      
      private
      def sheet_params
        params.require(:spree_sheet).permit(:file, :name, :header_row, :group_column)
      end

      def log(message=nil)
        return unless Rails.env.development? and message.present?
        @logger ||= Logger.new(File.join(Rails.root, 'log', 'debug.log'))
        @logger.debug(message) 
      end

    end
  end
end

app/views/spree/admin/sheets/_global_map.html.erb
<%= form_for sheet, as: :spree_sheet, url: admin_sheet_global_map_patch_path, remote: true do |f| %>
  
  <div id="global_map_props">
    <% if sheet.data and sheet.data['global_map'] and !sheet.data['global_map'].empty? %>
      <% sheet.data['global_map'].each do |item| %>
        <%= render partial: 'global_map_item', locals: {idx: item[0], item: item[1]} %>
      <% end %>
    <% end %>
  </div>

  <div class="form-group">
    <%= link_to admin_sheet_global_map_item_path(sheet.id), remote: true, method: :get, class: 'btn btn-sm btn-default' do %>
      <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Global Property
    <% end %>
  </div>

  <div class="form-group submit-group">
    <%= f.submit 'Save Global Mapping', class: 'btn btn-lg btn-success btn-block', tabindex: 3, disabled: false, id: 'submit_global_map' %>
  </div>
<% end %>

app/views/spree/admin/sheets/_global_map_item.html.erb
<% 
idx ||= (0...8).map { (65 + rand(26)).chr }.join 
item ||= {} 
%>

<div class="row flex-middle">
  <div class="col-xs-6 col-sm-5">
    <label for="src<%= idx %>">Key</label>
    <%= select_tag "global_map[#{idx}][key]", options_for_select(Spree::Sheet.product_props, item["key"]), class: 'form-control', id: "src#{idx}" %>

    <input type="text" id="prop<%= idx %>" name="global_map[<%= idx %>][prop_key]" class="globalMapSelect form-control" placeholder="Property name" autocomplete="new-password" style="<%= "display:none" if item["prop_key"].nil? %>" value="<%= item["prop_key"] %>" <%= "disabled" if item["prop_key"].nil? %> />
  </div>
  <div class="col-xs-1 hidden-xs global_map_arrow">
    <span class="glyphicon glyphicon-arrow-right" aria-hidden="true"></span>
  </div>
  <div class="col-xs-5">
    <label for="dest<%= idx %>">Value</label>
    <input type="text" id="dest<%= idx %>" name="global_map[<%= idx %>][dest]" autocomplete="new-password" class="form-control" value="<%= item["dest"] %>" <%= "disabled" if item["dest"].nil? %> />

  </div>

  <div class="col-xs-1">
    <button type="button" class="btn btn-danger btn-sm remove" id="remove_global_map_<%= idx %>" title="Remove Global Mapping">
      &times;
    </button>
  </div>

</div>
<script>
$(function() {

  $('#src<%= idx %>').on('change', function(e) {
    // console.log(this.value, this.selectedIndex)
    $('#dest<%= idx %>').prop('disabled', false).val('')
    $('#dest<%= idx %>').select2('destroy')

    if(this.selectedIndex === 0) {
      $('#dest<%= idx %>').prop('disabled', true)
      $('#dest<%= idx %>').addClass('form-control')
    } else if(this.value === 'property') {
      $('#prop<%= idx %>').prop('disabled', false).val('').prop('style','')
      $('#dest<%= idx %>').addClass('form-control')
    } else {
      $('#prop<%= idx %>').prop('disabled', true).val('').prop('style','display:none;')
      var global_map_prop = global_map_props[this.value]
      // console.log('global_map_prop: ', global_map_prop)
      if( global_map_props && global_map_prop && global_map_prop.data ){
        $('#dest<%= idx %>').removeClass('form-control')
        
        var select2_options = {
          tags: true,
          width: '100%',
          allowClear: true,
          selectOnBlur: true,
          multiple: global_map_prop.multiple,
          maximumSelectionSize: global_map_prop.multiple ? 999 : 1,
          placeholder: 'Click here and start typing.',
          data: global_map_prop.data
        }

        if(global_map_prop.require_choice !== true) {
          // allow for anything typed in to become the tagg'd value (y'know, like a <input type="text"/> lolol)
          select2_options['createSearchChoice'] = function(term, data) {
            if( $(data).filter( function() {
              return this.text.localeCompare(term)===0
            }).length===0 ) {
              return { id:term, text:term }
            }
          }
        }

        $('#dest<%= idx %>').select2(select2_options)
      }
    }

  })

  $('#remove_global_map_<%= idx %>').click(function(){
    $(this).closest('.row').remove()
  })

  
})
</script>

app/views/spree/admin/sheets/_header_map.html.erb
<%= form_for sheet, as: :spree_sheet, url: admin_sheet_header_map_patch_path, remote: true, :html => {id: 'header_map'} do |f| %>
  
  <div id="header_map_items">
    <% sheet.data["header_map"].each_with_index do |header, idx| %>
      <%= render partial: 'header_map_item', locals: {sheet: sheet, header: header[1], idx: idx} %>
    <% end unless sheet.data["header_map"].nil? %>
  </div>

  <div class="form-group">
    <%= link_to admin_sheet_header_map_item_path(@sheet.id), remote: true, method: :get, class: 'btn btn-sm btn-default' do %>
      <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Header Map Item
    <% end %>
  </div>

  <div class="form-group">
    <%= f.submit 'Save Header Mapping', class: 'btn btn-lg btn-success btn-block', tabindex: 3, disabled: false, id: 'submit_header_map' %>
  </div>
  
<% end %>

app/views/spree/admin/sheets/delete.js.erb
$("#sheet_<%= escape_javascript(@sheet_id) %>").remove();

app/views/spree/admin/sheets/edit.html.erb
<style>
.sheet dd {
  margin-left: 1em;
}
.global_map_arrow{
  margin-top: 20px;
}
.globalMapSelect{
  margin-top: 22px;
}
.submit-group {
  margin-top: 2em;
}
.flex-middle {
  display: flex;
  justify-content: center;
  align-items: center;
  transition: background-color 0.2s linear 0.2s;
}
.row.flex-middle:hover {
  background-color: #f7f7f7;
}
.btn-danger.remove {
  margin-top: 18px;
  color: #f43f3b;
  background-color: transparent;
}
.btn-danger.remove:hover {
  background-color: #f43f3b;
  color: white;
}
</style>

<% content_for :page_title do %>
  <%= @sheet.name %>
<% end %>

<% content_for :page_actions do %>
  <% if @sheet.active? or @sheet.ready? or @sheet.failed_processing? %>
    <div class="btn-group-vertical" role="group" aria-label="sheet actions">
      <%# button_link_to 'Process File', admin_process_sheet_path(@sheet.id), { class: "btn-default", icon: 'file', id: 'admin_new_sheet' } %>
      <%= button_link_to 'Import Products', admin_import_products_sheet_path(@sheet.id), { class: "btn-primary", icon: 'import', id: 'admin_import_products_sheet' } %>
    </div>
  <% end %>
<% end if can?(:create, Spree::Sheet) %>

<% if @sheet.processing? %>

<div class="progress">
  <div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%" id="sheet_progress">
    <span class="sr-only">Processing</span>
  </div>
</div>

<h3>Processing... <small id="sheet_progress_percent"></small></h3>

<script>
var intervalRate = 1000
var intervalThrottle = 1

;(function checkStatus(){
  window.setTimeout(function(){
    if(intervalThrottle < 60){
      intervalThrottle += 1
    }
    fetch('<%= admin_sheet_status_url %>')
    .then(function(r) {
      return r.json()
    })
    .then(function(response) {
      // console.log(JSON.stringify(response))
      if(response.status !== 'processing'){
        window.location.reload(false)
      }
      var progress = parseFloat(response.progress) * 100 || 0

      $("#sheet_progress").prop('style','width: '+progress+'%').prop('aria-valuenow', progress)
      $("#sheet_progress_percent").html('('+progress+'%)')
      checkStatus()
    })
  }, intervalRate * intervalThrottle)
})()
</script>

<% else %>
<div class="row">
  <div class="col-md-6">
    <dl class="sheet">
      <dt>Status</dt>
      <dd><span class="label <%= @sheet.status_class %>"><%= @sheet.status %></span></dd>
      <dt>Created</dt>
      <dd><%= t @sheet.created_at %></dd>
      <dt>Updated</dt>
      <dd><%= t @sheet.updated_at %></dd>
      <% if @sheet.rows %>
        <dt>Rows</dt>
        <dd><%= number_with_delimiter(@sheet.rows, :delimiter => ',') %></dd>
      <% end %>
    </dl>
  </div>
  <div class="col-md-6">
    <%= form_for @sheet, as: :spree_sheet, url: admin_update_sheet_path do |f| %>
      <div class="form-group">
        <%= f.label :header_row do %>
          Header Row Number
          <%= f.number_field :header_row, class: 'form-control', tabindex: 1, placeholder: 'Header Row Number' %>
        <% end %>
      </div>
      
      <div class="btn-group-vertical" role="group" aria-label="header actions">
        <%= f.submit 'Update Header Row', class: 'btn btn-success', tabindex: 2, disabled: false, id: 'update_sheet' %>

        <%= button_link_to 'Refetch Headers', admin_process_headers_path(@sheet.id), { class: "btn-default", id: 'admin_process_headers' } %>
        <% unless @sheet.data["headers"].blank? %>
          <a class="btn btn-default" role="button" data-toggle="collapse" href="#collapseHeaders" aria-expanded="false" aria-controls="collapseHeaders">
            Show Headers
          </a>
        <% end %>
      </div>
    <% end %>
      <% unless @sheet.data["headers"].blank? %>
       
        <div class="collapse" id="collapseHeaders">
          <div class="well">
            <%= @sheet.data["headers"].join(', ') %>
          </div>
        </div>

    <% end %>
  </div>

</div>

<div class="row">
  <div class="col-md-8 col-md-offset-1">

    <ul class="nav nav-pills">
      <li><h4>Global Mapping</h4></li>
      <% if Spree::Sheet.count > 1 %>
      <li role="presentation" class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
          <span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
          <li><a href="#">Load Global Mapping Preset</a></li>
          <li role="separator" class="divider"></li>
        </ul>
      </li>
      <% end %>
    </ul>

    <br/>

    <div id="global_map_container">
      <%= render partial: 'global_map', locals: {sheet: @sheet} %>
    </div>
    
  </div>
</div>
<div class="row">
  <div class="col-md-8 col-md-offset-1">
    <% if @sheet.data and @sheet.data['headers'] and !@sheet.data['headers'].empty? %>
   
      <ul class="nav nav-pills">
        <li><h4>Header Mapping</h4></li>
        <% if Spree::Sheet.count > 1 %>
        <li role="presentation" class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li><a href="#">Load Header Mapping Preset</a></li>
            <li role="separator" class="divider"></li>
          </ul>
        </li>
        <% end %>
      </ul>

      <br/>
      <div id="header_map_container">
        <%= render partial: 'header_map', locals: {sheet: @sheet} %>
      </div>
    <% end %>
  </div>
</div>

<% unless @sheet.data["history"].blank? %>
<div class="row">
  <h3>History</h3>
  <% @sheet.data["history"].reverse.each do |entry| %>
    <div class="panel <%= entry["error"].blank? ? 'panel-default' : 'panel-danger' %>">
      <div class="panel-heading">
        <h3 class="panel-title"> <%= DateTime.strptime(entry["date"], '%Y-%m-%dT%H:%M:%S.%L%z').to_formatted_s(:long) rescue '' %></h3>
      </div>
      <div class="panel-body">
        <%= entry["success"] %>
        <%= entry["error"] %>
      </div>
    </div>
  <% end %>
</div>
<% end %>

<script>
var global_map_props = <%= Spree::Sheet.global_map_props.to_json.html_safe %>;
var headers = <%= @sheet.data["headers"].to_json.html_safe %>;
var headers_for_select = <%= @sheet.data["headers"].each_with_index.map{|v,i| {id: i, text: v}}.to_json.html_safe rescue 'undefined' %>;
</script>
<% end %>

app/views/spree/admin/sheets/global_map_item.js.erb
$("<%= escape_javascript(render 'global_map_item') %>").appendTo("#global_map_props");

app/views/spree/admin/sheets/index.html.erb
<% content_for :page_title do %>
  Sheets
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to 'New Sheet', admin_new_sheet_path, { class: "btn-success", icon: 'add', id: 'admin_new_sheet' } %>
<% end if can?(:create, Spree::Sheet) %>


<table class="table">
<thead>
  <tr>
    <td>Name</td>
    <td>Created</td>
    <td></td>
    <td></td>
  </tr>
</thead>
<% @sheets.each do |sheet| %>
    <tr class="sheet" id="sheet_<%= sheet.id %>">
      <td><%= link_to sheet.name, admin_edit_sheet_path(sheet.id) %></td>
      <td><%= sheet.created_at.to_formatted_s(:long) %></td>
      <td>
        <span class="label <%= sheet.status_class %>"><%= sheet.status %></span> 
        <%= "#{number_with_delimiter(sheet.rows, :delimiter => ',')} Rows" if sheet.rows %>
      </td>
      <td>
      <% if sheet.processing? %>
      <div class="spinner-border spinner-border-sm" role="status">
        <span class="sr-only">Processing...</span>
      </div>
      <% else %>
        <%= link_to admin_delete_sheet_path(sheet.id), remote: true, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure?' } do %>
            <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
        <% end %>
      <% end %>
      
      </td>
    </tr>
<% end %>
</table>

<%= paginate @sheets %>

app/views/spree/admin/sheets/new.html.erb
<style>
#drop{
	border:2px dashed #bbb;
	-moz-border-radius:5px;
	-webkit-border-radius:5px;
	border-radius:5px;
	padding:25px;
	text-align:center;
	font:20pt bold,sans-serif;
  color:#bbb
}
</style>

<% content_for :page_title do %>
  Upload New Sheet
<% end %>

<%= form_for Spree::Sheet.new, as: :spree_sheet, url: admin_create_new_sheet_path do |f| %>
  <fieldset id="password-credentials">
    <%= f.hidden_field :name %>

    <div id="drop">Drop a spreadsheet file here</div>
    <div class="form-group">
      <%= f.file_field :file %>
    </div>

    <div class="form-group">
      <%= f.label :header_row do %>
        Header Row
        <%= f.number_field :header_row, class: 'form-control', tabindex: 1, placeholder: 'Header Row' %>
      <% end %>
    </div>

    <div class="form-group">
      <%= f.submit 'Upload Sheet', class: 'btn btn-lg btn-success btn-block', tabindex: 3, disabled: true, id: 'submit_new_sheet' %>
    </div>
  </fieldset>
<% end %>

<script>
(function() {

	var drop = document.getElementById('drop')
  var file_input = document.getElementById('spree_sheet_file')
  var sheet_name = document.getElementById('spree_sheet_name')
  var submit_new_sheet = document.getElementById('submit_new_sheet')

	if(!drop.addEventListener) return

	function handleDrop(e) {
		e.stopPropagation()
    e.preventDefault()
    file_input.files = e.dataTransfer.files
    sheet_name.value = e.dataTransfer.files[0].name
    submit_new_sheet.disabled = false
	}
	function handleDragover(e) {
		e.stopPropagation()
		e.preventDefault()
		e.dataTransfer.dropEffect = 'copy'
	}
	drop.addEventListener('dragenter', handleDragover, false)
	drop.addEventListener('dragover', handleDragover, false)
	drop.addEventListener('drop', handleDrop, false)

  file_input.addEventListener('change', function(e){
    sheet_name.value = e.target.files[0].name
    submit_new_sheet.disabled = false
  }, false)

})()
</script>